# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'solutionwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import QCoreApplication ,QMetaObject, QRect
from PySide2.QtGui import QFont
from PySide2.QtWidgets import QTextBrowser, QPushButton


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(501, 259)
        Form.setStyleSheet(u"QWidget#frmLogin,QWidget#frmPopup,QWidget#frmHostInfo,QWidget#frmLogout,QWidget#frmConfig,QWidget#frmData,QWidget#frmDefence,QWidget#frmHost,QWidget#frmMain,QWidget#frmPwd,QWidget#frmSelect,QWidget#frmMessageBox{\n"
"	border:1px solid #0F7DBE;\n"
"	border-radius:0px;	\n"
"}\n"
"\n"
".QFrame{\n"
"	border:1px solid #50A3F0;\n"
"	border-radius:5px;\n"
"}\n"
"\n"
"QWidget#widget_title{\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3);\n"
"}\n"
"\n"
"QLabel#lab_Ico,QLabel#lab_Title{\n"
"	border-radius:0px;\n"
"	color: #F0F0F0;\n"
"	background-color:rgba(0,0,0,0);\n"
"	border-style:none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"	border: 1px solid #50A3F0;\n"
"	border-radius: 5px;\n"
"	padding: 2px;\n"
"	background: none;\n"
"	selection-background-color: #0F7DBE;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { \n"
"	lineedit-password-character: 9679; \n"
"}\n"
"\n"
".QGroupBox{\n"
"	border: 1px solid #50A3F0;\n"
"	border-radius: 5px;\n"
"}\n"
"\n"
".QPushButton{\n"
"	border-style:"
                        " none;\n"
"	border: 0px;\n"
"	color: #F0F0F0;\n"
"	padding: 5px;	\n"
"	min-height: 20px;\n"
"	border-radius:5px;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3); \n"
"}\n"
"\n"
".QPushButton[focusPolicy=\"0\"] {\n"
"	border-style: none;\n"
"	border: 0px;\n"
"	color: #F0F0F0;\n"
"	padding: 0px;	\n"
"	min-height: 10px;\n"
"	border-radius:3px;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3); \n"
"}\n"
"\n"
".QPushButton:hover{ \n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #50A3F0, stop:1 #489CEA);\n"
"}\n"
"\n"
".QPushButton:pressed{ \n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3);\n"
"}\n"
"\n"
"QPushButton#btnMenu,QPushButton#btnMenu_Min,QPushButton#btnMenu_Max,QPushButton#btnMenu_Close{\n"
"	border-radius:0px;\n"
"	color: #F0F0F0;\n"
"	background-color:rgba(0,0,0,0);\n"
"	border-style:none;\n"
"}\n"
"\n"
"QPushButton#btnMe"
                        "nu:hover,QPushButton#btnMenu_Min:hover,QPushButton#btnMenu_Max:hover{\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(25, 134, 199, 0), stop:1 #50A3F0);\n"
"}\n"
"\n"
"QPushButton#btnMenu_Close:hover{\n"
"	background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(238, 0, 0, 128), stop:1 rgba(238, 44, 44, 255));\n"
"}\n"
"\n"
"QCheckBox {\n"
"	spacing: 2px; \n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"	width: 20px;\n"
"	height: 20px;\n"
"}\n"
"\n"
"\n"
"QRadioButton {\n"
"	spacing: 2px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"	width: 15px; \n"
"	height: 15px; \n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"	image: url(:/qss_icons/img_rc/radio_normal.png); \n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"	image: url(:/qss_icons/img_rc/radio_selected.png); \n"
"}\n"
"\n"
"QComboBox,QDateEdit{\n"
"	border-radius: 3px;\n"
"	padding: 1px 10px 1px 5px;\n"
"	border: 1px solid #50A3F0;\n"
"}\n"
"\n"
"QComboBox::drop-down,QDateEdit::drop-do"
                        "wn {\n"
"	subcontrol-origin: padding;\n"
"	subcontrol-position: top right;\n"
"	width: 15px; \n"
"	border-left-width: 1px;\n"
"	border-left-style: solid;\n"
"	border-top-right-radius: 3px;\n"
"	border-bottom-right-radius: 3px;\n"
"	border-left-color: #50A3F0;\n"
"}\n"
"\n"
"QComboBox::down-arrow,QDateEdit::down-arrow {\n"
"	image: url(:/qss_icons/img_rc/array_down.png); \n"
"}\n"
"\n"
"QMenu {\n"
"	background-color:#F0F0F0;\n"
"	margin: 2px;\n"
"}\n"
"\n"
"QMenu::item {	\n"
"	padding: 2px 12px 2px 12px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"	width: 13px;\n"
"	height: 13px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"	color: #F0F0F0;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3); \n"
"}\n"
"\n"
"QMenu::separator {\n"
"	height: 1px;\n"
"	background: #50A3F0;\n"
"}\n"
"\n"
"QProgressBar {\n"
"	border-radius: 5px;\n"
"	text-align: center;\n"
"	border: 1px solid #50A3F0;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"	width: 5px; \n"
"	margin: 0.5px;\n"
"	background-co"
                        "lor: #0F7DBE;\n"
"}\n"
"\n"
"QSlider::groove:horizontal,QSlider::add-page:horizontal { \n"
"	background: #808080; \n"
"	height: 8px; \n"
"	border-radius: 3px; \n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"	height: 8px; \n"
"	border-radius: 3px;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3); \n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"	width: 13px; \n"
"	margin-top: -3px; \n"
"	margin-bottom: -3px; \n"
"	border-radius: 6px;\n"
"	background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,stop:0.6 #F0F0F0, stop:0.778409 #50A3F0);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"	background: qradialgradient(spread: pad, cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, stop: 0.6 #F0F0F0,stop:0.778409 #0F7DBE);\n"
"}\n"
"\n"
"QSlider::groove:vertical,QSlider::sub-page:vertical {\n"
"	background:#808080; \n"
"	width: 8px; \n"
"	border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"	width: 8px;\n"
"	border-radiu"
                        "s: 3px;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3); \n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"	height: 14px; \n"
"	margin-left: -3px;\n"
"	margin-right: -3px;\n"
"	border-radius: 6px;\n"
"	background: qradialgradient(spread: pad, cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, stop: 0.6 #F0F0F0, stop:0.778409 #50A3F0);\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"	background: qradialgradient(spread: pad, cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, stop: 0.6 #F0F0F0,stop:0.778409 #0F7DBE);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"	width:10px; \n"
"	background-color:rgba(0,0,0,0%); \n"
"	padding-top:10px; \n"
"	padding-bottom:10px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"	height:10px; \n"
"	background-color:rgba(0,0,0,0%); \n"
"	padding-left:10px; padding-right:10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"	width:10px;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #50A3F0, stop:1 #489CEA); \n"
"}"
                        "\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"	height:10px;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #50A3F0, stop:1 #489CEA); \n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"	width:10px;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3); \n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"	height:10px;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3); \n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"	height:10px;\n"
"	width:10px;\n"
"	subcontrol-position: bottom; \n"
"	subcontrol-origin: margin;\n"
"	border-image:url(:/qss_icons/img_rc/add-line_vertical.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"	height:10px;\n"
"	width:10px;\n"
"	subcontrol-position: right;\n"
"	subcontrol-origin: margin;\n"
"	border-image:url(:/qss_icons/img_rc/add-line_horizontal.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"	height:10px;\n"
"	width:10px;\n"
"	"
                        "subcontrol-position: top; \n"
"	subcontrol-origin: margin;\n"
"	border-image:url(:/qss_icons/img_rc/sub-line_vertical.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"	height:10px;\n"
"	width:10px;\n"
"	subcontrol-position: left;\n"
"	subcontrol-origin: margin;\n"
"	border-image:url(:/qss_icons/img_rc/sub-line_horizontal.png);\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical {\n"
"	width:10px;\n"
"	background: #C0C0C0;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal {\n"
"	height:10px;\n"
"	background: #C0C0C0;\n"
"}\n"
"\n"
"QScrollArea {\n"
"	border: 0px ; \n"
"}\n"
"\n"
"QTreeView,QListView,QTableView{\n"
"	border: 1px solid #50A3F0; \n"
"	selection-background-color: #0F7DBE;\n"
"	selection-color: #F0F0F0;\n"
"}\n"
"\n"
"QTableView::item:selected, QListView::item:selected, QTreeView::item:selected {\n"
"	color: #F0F0F0;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3); \n"
"}\n"
"\n"
"QTabl"
                        "eView::item:hover, QListView::item:hover, QTreeView::item:hover {\n"
"	color: #F0F0F0;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #50A3F0, stop:1 #489CEA); \n"
"}\n"
"\n"
"QTableView::item, QListView::item, QTreeView::item {\n"
"	padding: 5px; \n"
"	margin: 0px; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"	padding:3px;\n"
"	margin:0px;\n"
"	color:#F0F0F0;\n"
"	border: 1px solid #F0F0F0;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #50A3F0, stop:1 #489CEA);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"	border-bottom-left-radius:0px;\n"
"	border-bottom-right-radius:0px;\n"
"	color: #F0F0F0;\n"
"	min-width: 60px;\n"
"	min-height: 20px;\n"
"	padding: 3px 8px 3px 8px;\n"
"	margin:1px;\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #50A3F0, stop:1 #489CEA); \n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"	background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #0F7DBE, stop:1 #1582C3); \n"
"}\n"
"\n"
"QSta"
                        "tusBar::item {\n"
"     border: 1px solid #50A3F0;\n"
"     border-radius: 3px;\n"
"}\n"
"QToolButton#add_row,#add_column{\n"
"qproperty-icon:url(:/icons/images/plus.png);\n"
"background-color:rgba(0,0,0,0);\n"
"}\n"
"QToolButton#remove_row,#remove_column{\n"
"qproperty-icon:url(:/icons/images/minus.png);\n"
"background-color:rgba(0,0,0,0);\n"
"}")
        self.solution_text = QTextBrowser(Form)
        self.solution_text.setObjectName(u"solution_text")
        self.solution_text.setGeometry(QRect(10, 10, 481, 183))
        self.ok_button = QPushButton(Form)
        self.ok_button.setObjectName(u"ok_button")
        self.ok_button.setGeometry(QRect(200, 212, 91, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ok_button.setFont(font)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.solution_text.setHtml(QCoreApplication.translate("Form", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.ok_button.setText(QCoreApplication.translate("Form", u"ok", None))
    # retranslateUi

